AWSTemplateFormatVersion: "2010-09-09"
Description: Amazon Lex Bot with Lambda Integration

Resources:
  LexLambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: LexLambdaRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: LexLambdaPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                Resource: "*"

  LexLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: LexLambdaFunction
      Runtime: python3.8
      Role: !GetAtt LexLambdaRole.Arn
      Handler: index.lambda_handler
      Code:
        ZipFile: |
          import json
          import boto3

          def lambda_handler(event, context):
              intent_name = event['currentIntent']['name']
              s3_bucket = 'lexsmapledata'
              s3_object_key = 'sample.json'
              
              s3 = boto3.client('s3')
              response = s3.get_object(Bucket=s3_bucket, Key=s3_object_key)
              data = json.loads(response['Body'].read().decode())
              
              if intent_name in data:
                  bot_response = data[intent_name]['response']
              else:
                  bot_response = "I'm sorry, I couldn't find the information you're looking for."
              
              return {
                  'dialogAction': {
                      'type': 'Close',
                      'fulfillmentState': 'Fulfilled',
                      'message': {
                          'contentType': 'PlainText',
                          'content': bot_response
                      }
                  }
              }

Outputs:
  LambdaFunctionArn:
    Description: The ARN of the Lambda function.
    Value: !GetAtt LexLambdaFunction.Arn
